### ISSUE TITLE
Callback error updating short-data-graph.figure, short-data-graph-raw.figure, short-data-table.figure

### ISSUE THREAD

**Issue by whispy** [Caesurus/short_volume#2]
**Issue**
When first loading the app with no ticker symbol selected, it shows the error `Callback error updating short-data-graph.figure, short-data-graph-raw.figure, short-data-table.figure`. The full error text (with API token removed):
```
Traceback (most recent call last):
  File "/Users/me/venvs/short_venv/short_volume-main/render_chart.py", line 46, in update_graph
    df_symbol_open_close = pd.read_json(URL)
  File "/Users/me/venvs/short_venv/lib/python3.9/site-packages/pandas/util/_decorators.py", line 199, in wrapper
    return func(*args, **kwargs)
  File "/Users/me/venvs/short_venv/lib/python3.9/site-packages/pandas/util/_decorators.py", line 299, in wrapper
    return func(*args, **kwargs)
  File "/Users/me/venvs/short_venv/lib/python3.9/site-packages/pandas/io/json/_json.py", line 540, in read_json
    json_reader = JsonReader(
  File "/Users/me/venvs/short_venv/lib/python3.9/site-packages/pandas/io/json/_json.py", line 622, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/Users/me/venvs/short_venv/lib/python3.9/site-packages/pandas/io/json/_json.py", line 659, in _get_data_from_filepath
    self.handles = get_handle(
  File "/Users/me/venvs/short_venv/lib/python3.9/site-packages/pandas/io/common.py", line 558, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/Users/me/venvs/short_venv/lib/python3.9/site-packages/pandas/io/common.py", line 289, in _get_filepath_or_buffer
    req = urlopen(filepath_or_buffer)
  File "/Users/me/venvs/short_venv/lib/python3.9/site-packages/pandas/io/common.py", line 195, in urlopen
    return urllib.request.urlopen(*args, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1385, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1342, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1266, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1100, in putrequest
    self._validate_path(url)
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1200, in _validate_path
    raise InvalidURL(f"URL can't contain control characters. {url!r} "
http.client.InvalidURL: URL can't contain control characters. '/tiingo/daily/Pick Symbol to track/prices?startDate=nan&endDate=nan&token={TOKENREMOVED}' (found at least ' ')
```

**Possible Cause**
The app is sending "pick symbol to track" as part of the data request to Tiingo.

**Solution**
On initial app run, use first ticker in list. (More advanced: On subsequent runs, store last used ticker in DB and use that when running app).

**Comment by Caesurus** [comment]
Should be fixed now.
